# Generated by Django 5.2.7 on 2025-11-04 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duración estimada en minutos', validators=[django.core.validators.MinValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('CONF', 'Confirmado'), ('CANC', 'Cancelado')], default='PEND', max_length=4)),
                ('notas', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turnos.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turnos.servicio')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
